LOAD DATA
INFILE 'YourProjectPath\01-Basic\employees.csv'
TRUNCATE 
INTO TABLE employees
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
DATE FORMAT 'DD-MON-YYYY'
TRAILING NULLCOLS
(
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    HIRE_DATE DATE,
    SALARY,
    DEPARTMENT_ID
)


